-- Minimal schema for long-term storage in Supabase Postgres.
-- Run this in Supabase SQL editor.

create table if not exists telemetry_readings (
  id bigint generated by default as identity primary key,
  warehouse_id text not null,
  ts_ms bigint not null,
  temperature_c double precision not null,
  humidity_pct double precision not null,
  created_at timestamptz not null default now()
);

-- Avoid duplicates when multiple clients are running.
create unique index if not exists telemetry_readings_unique
on telemetry_readings (warehouse_id, ts_ms);

create table if not exists inventory_events (
  id bigint generated by default as identity primary key,
  warehouse_id text not null,
  ts_ms bigint not null,
  scan_type text not null,
  scan_code text not null,
  created_at timestamptz not null default now()
);

create index if not exists inventory_events_warehouse_ts
on inventory_events (warehouse_id, ts_ms desc);

-- NOTE: For demo you may disable RLS or add policies.
-- alter table telemetry_readings disable row level security;
-- alter table inventory_events disable row level security;
